In [ ]:
from __future__ import print_function
import patsy
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import tensorflow as tf
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.optimizers import Adam
from keras.models import Sequential
from keras.layers import Dense
#from keras.optimizers import Adam
from keras.callbacks import EarlyStopping

from keras.layers import Dense
from keras.regularizers import l1
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

import os
import sys
import warnings
import xlrd 
import numpy as  np
import pandas as pd
from math import sqrt
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [ ]:
%matplotlib inline

In [ ]:
headers = ["voltage","temperature","frequency"]
data = pd.read_csv('Colpits_Dataset.csv', na_values='?',    
         header=None,names = headers) 
data = data.reset_index(drop=True)
data = data.iloc[1:] 
data= data.dropna()
data.head()

voltage temperature    frequency
1       5          20  1005950.515
2       5          21  1012194.995
3       5          22  1017407.592
4       5          23  1023204.753
5       5          24  1029339.752

In [ ]:
data["voltage"]= pd.to_numeric(data['voltage'],errors = 'coerce')
data['temperature'] = pd.to_numeric(data['temperature'],errors = 'coerce')
data['frequency'] = pd.to_numeric(data['frequency'],errors = 'coerce')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2091 entries, 1 to 2091
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   voltage      2091 non-null   float64
 1   temperature  2091 non-null   int64  
 2   frequency    2091 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 49.1 KB


In [ ]:
x= data.drop(['frequency'],axis=1).values
y = data['frequency'].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
from sklearn.preprocessing import StandardScaler
sum = 0
dev = 0
stddev = [0,0]
means = [0,0]

scale =1000000
y_train /= scale
y_test /= scale
# 
# y_train /= np.amax(y_train)
# y_test /= np.amax(y_test)

size = len(x_train+1)
print(size)
for i in range (2):
  sum = 0
  for j in range (size):
    sum += x_train[j][i]/size
  means[i] = sum

for i in range (2):
  dev = 0
  for j in range (size):
    dev = dev + ((x_train[j][i]-means[i])**2)/(size-1)
  stddev[i] = sqrt(dev)

print(means)
print(stddev)
#print(x_train[0:4])
scaler= StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
#print(x_train[0:4])
print(len(x_test))
print(len(y_test))
print(len(x_train))
print(len(y_train))

1672
[7.523026315789461, 40.08851674641164]
[1.4705534742238435, 11.845678850686074]
419
419
1672
1672


In [ ]:
x_test.shape

(419, 2)

In [ ]:
x_train = pd.DataFrame(x_train)
x_test = pd.DataFrame(x_test)
y_train = pd.DataFrame(y_train)
y_test = pd.DataFrame(y_test)
print(x_train)
print(y_train)

             0         1
0     1.208732 -0.851917
1     0.256425  1.512521
2     0.732579  0.330302
3     0.664557 -1.274138
4    -0.355773 -0.345252
...        ...       ...
1667 -1.512146 -0.514140
1668  0.392469  0.583635
1669  1.616864 -0.514140
1670  1.344776  1.343633
1671  1.344776  0.752523

[1672 rows x 2 columns]
             0
0     1.064097
1     1.362990
2     1.183487
3     1.031450
4     1.111737
...        ...
1667  1.098147
1668  1.215172
1669  1.093080
1670  1.330721
1671  1.237022

[1672 rows x 1 columns]


In [ ]:
from tensorflow.keras.optimizers import Adam, SGD, RMSprop, Adadelta, Adamax, Nadam, Ftrl
from keras.models import Sequential
from keras.layers import Dense, Dropout
import keras
model= Sequential()
model.add(Dense(4,  activation=keras.layers.LeakyReLU(alpha=0.1), input_dim=2))
model.add(Dense(2,  activation=keras.layers.LeakyReLU(alpha=0.1)))
model.add(Dense(1))

In [ ]:
model.compile(Adam(learning_rate=0.01), 'mse')#,metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, validation_data=(x_test,y_test),batch_size=8, epochs=100)

Epoch 1/100
209/209 [==============================] - 3s 5ms/step - loss: 0.1359 - val_loss: 8.3021e-04
Epoch 2/100
209/209 [==============================] - 1s 4ms/step - loss: 3.1512e-04 - val_loss: 1.5485e-04
Epoch 3/100
209/209 [==============================] - 1s 3ms/step - loss: 8.6886e-05 - val_loss: 5.3082e-05
Epoch 4/100
209/209 [==============================] - 1s 3ms/step - loss: 3.8255e-05 - val_loss: 2.6669e-05
Epoch 5/100
209/209 [==============================] - 1s 2ms/step - loss: 2.5646e-05 - val_loss: 2.0009e-05
Epoch 6/100
209/209 [==============================] - 0s 2ms/step - loss: 2.0443e-05 - val_loss: 1.5168e-05
Epoch 7/100
209/209 [==============================] - 0s 2ms/step - loss: 1.6687e-05 - val_loss: 1.4138e-05
Epoch 8/100
209/209 [==============================] - 0s 2ms/step - loss: 1.4910e-05 - val_loss: 1.3617e-05
Epoch 9/100
209/209 [==============================] - 0s 2ms/step - loss: 1.3176e-05 - val_loss: 1.2589e-05
Epoch 10/100
209/209 [=

In [ ]:
model.summary()
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from math import sqrt

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 4)                 12        
                                                                 
 dense_7 (Dense)             (None, 2)                 10        
                                                                 
 dense_8 (Dense)             (None, 1)                 3         
                                                                 
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [ ]:
y_pred = model.predict(x_test)

# print(y_pred*scale)
MSE=mean_squared_error(y_test, y_pred)
print("Mean squared error     :", MSE)

RMSE=sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean squared error:", RMSE)

MAE=mean_absolute_error(y_test, y_pred)
print("Mean Absolute error    :", MAE)

print("R2 score    :", r2_score(y_test,  y_pred))

14/14 [==============================] - 0s 2ms/step
Mean squared error     : 2.0523059452064487e-05
Root Mean squared error: 0.004530238343847318
Mean Absolute error    : 0.004078817776201271
R2 score    : 0.9983679209024234


In [ ]:
model.save('Colpitts_model.h5')

In [ ]:
print(y_pred[14:24])

[[1.0493929]
 [1.2369566]
 [1.0246425]
 [1.0995052]
 [1.2648269]
 [1.0924212]
 [1.27913  ]
 [1.2178614]
 [1.2652917]
 [1.0131289]]


In [ ]:
print(y_test[14:24])

           0
14  1.043652
15  1.238064
16  1.021900
17  1.096814
18  1.261454
19  1.089184
20  1.275271
21  1.216825
22  1.261628
23  1.001383


In [ ]:
print("Weights and biases of the layers after training the model: \n")
for layer in model.layers:
  print(layer.name)
  print("Weights")
  print("Shape: ",layer.get_weights()[0].shape,'\n',layer.get_weights()[0])
  print("Bias")
  print("Shape: ",layer.get_weights()[1].shape,'\n',layer.get_weights()[1],'\n')

Weights and biases of the layers after training the model: 

dense_6
Weights
Shape:  (2, 4) 
 [[ 8.4985942e-03 -4.8610666e-03  2.1839321e-03  5.8259163e-04]
 [ 6.2884718e-01  3.7706763e-01 -2.3587153e-04 -4.5336583e-01]]
Bias
Shape:  (4,) 
 [-0.46556187  0.6006878  -0.00643603 -0.17260675] 

dense_7
Weights
Shape:  (4, 2) 
 [[ 0.07293656 -0.74979895]
 [ 0.5258293   0.56097907]
 [-0.00783858 -0.06836054]
 [ 0.15467049  0.2779006 ]]
Bias
Shape:  (2,) 
 [ 0.5245291  -0.52947783] 

dense_8
Weights
Shape:  (2, 1) 
 [[ 0.62905735]
 [-0.7078987 ]]
Bias
Shape:  (1,) 
 [0.6156947] 



In [ ]:
# Convert the model to the TensorFlow Lite format without quantization
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the model to disk
open("Colpitts_model.tflite", "wb").write(tflite_model)
  
import os
basic_model_size = os.path.getsize("Colpitts_model.tflite")
print("Model is %d bytes" % basic_model_size)
  
  

Model is 2320 bytes


In [ ]:
!echo "const unsigned char model[] = {" > /content/model.h
!cat Colpitts_model.tflite | xxd -i      >> /content/model.h
!echo "};"                              >> /content/model.h

import os
model_h_size = os.path.getsize("model.h")
print(f"Header file, model.h, is {model_h_size:,} bytes.")
print("\nOpen the side panel (refresh if needed). Double click model.h to download the file.")

Header file, model.h, is 14,342 bytes.

Open the side panel (refresh if needed). Double click model.h to download the file.
